# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x03llm\"\xa6\x01\n\x0fGenerateRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x33\n\x14\x63onversation_history\x18\x03 \x03(\x0b\x32\x15.llm.ConversationTurn\x12\x15\n\rsystem_prompt\x18\x04 \x01(\t\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x12\n\nmax_tokens\x18\x06 \x01(\x05\"3\n\x10\x43onversationTurn\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x11\n\tassistant\x18\x02 \x01(\t\"V\n\x10GenerateResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x13\n\x0btokens_used\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\"\'\n\x16GenerateStreamResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\t2\x8c\x01\n\nLLMService\x12\x37\n\x08Generate\x12\x14.llm.GenerateRequest\x1a\x15.llm.GenerateResponse\x12\x45\n\x0eGenerateStream\x12\x14.llm.GenerateRequest\x1a\x1b.llm.GenerateStreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=27
  _globals['_GENERATEREQUEST']._serialized_end=193
  _globals['_CONVERSATIONTURN']._serialized_start=195
  _globals['_CONVERSATIONTURN']._serialized_end=246
  _globals['_GENERATERESPONSE']._serialized_start=248
  _globals['_GENERATERESPONSE']._serialized_end=334
  _globals['_GENERATESTREAMRESPONSE']._serialized_start=336
  _globals['_GENERATESTREAMRESPONSE']._serialized_end=375
  _globals['_LLMSERVICE']._serialized_start=378
  _globals['_LLMSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
