# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x03rag\"<\n\x15IngestDocumentRequest\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"v\n\x16IngestDocumentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x03 \x01(\x05\x12\x11\n\tfile_type\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"]\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x33\n\x14\x63onversation_history\x18\x02 \x03(\x0b\x32\x15.rag.ConversationTurn\x12\t\n\x01k\x18\x03 \x01(\x05\"3\n\x10\x43onversationTurn\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x11\n\tassistant\x18\x02 \x01(\t\"S\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x1c\n\x07sources\x18\x02 \x03(\x0b\x32\x0b.rag.Source\x12\x14\n\x0c\x63ontext_used\x18\x03 \x01(\x08\"H\n\x06Source\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x17\n\x0frelevance_score\x18\x03 \x01(\x02\"\x11\n\x0fGetStatsRequest\"A\n\x10GetStatsResponse\x12\x17\n\x0ftotal_documents\x18\x01 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x05\x32\xc0\x01\n\nRAGService\x12I\n\x0eIngestDocument\x12\x1a.rag.IngestDocumentRequest\x1a\x1b.rag.IngestDocumentResponse\x12.\n\x05Query\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponse\x12\x37\n\x08GetStats\x12\x14.rag.GetStatsRequest\x1a\x15.rag.GetStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTDOCUMENTREQUEST']._serialized_start=26
  _globals['_INGESTDOCUMENTREQUEST']._serialized_end=86
  _globals['_INGESTDOCUMENTRESPONSE']._serialized_start=88
  _globals['_INGESTDOCUMENTRESPONSE']._serialized_end=206
  _globals['_QUERYREQUEST']._serialized_start=208
  _globals['_QUERYREQUEST']._serialized_end=301
  _globals['_CONVERSATIONTURN']._serialized_start=303
  _globals['_CONVERSATIONTURN']._serialized_end=354
  _globals['_QUERYRESPONSE']._serialized_start=356
  _globals['_QUERYRESPONSE']._serialized_end=439
  _globals['_SOURCE']._serialized_start=441
  _globals['_SOURCE']._serialized_end=513
  _globals['_GETSTATSREQUEST']._serialized_start=515
  _globals['_GETSTATSREQUEST']._serialized_end=532
  _globals['_GETSTATSRESPONSE']._serialized_start=534
  _globals['_GETSTATSRESPONSE']._serialized_end=599
  _globals['_RAGSERVICE']._serialized_start=602
  _globals['_RAGSERVICE']._serialized_end=794
# @@protoc_insertion_point(module_scope)
