# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\x03stt\"Y\n\x11TranscribeRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0c\n\x04task\x18\x04 \x01(\t\"S\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"=\n\x15\x44\x65tectLanguageRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"]\n\x16\x44\x65tectLanguageResponse\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\x96\x01\n\nSTTService\x12=\n\nTranscribe\x12\x16.stt.TranscribeRequest\x1a\x17.stt.TranscribeResponse\x12I\n\x0e\x44\x65tectLanguage\x12\x1a.stt.DetectLanguageRequest\x1a\x1b.stt.DetectLanguageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=26
  _globals['_TRANSCRIBEREQUEST']._serialized_end=115
  _globals['_TRANSCRIBERESPONSE']._serialized_start=117
  _globals['_TRANSCRIBERESPONSE']._serialized_end=200
  _globals['_DETECTLANGUAGEREQUEST']._serialized_start=202
  _globals['_DETECTLANGUAGEREQUEST']._serialized_end=263
  _globals['_DETECTLANGUAGERESPONSE']._serialized_start=265
  _globals['_DETECTLANGUAGERESPONSE']._serialized_end=358
  _globals['_STTSERVICE']._serialized_start=361
  _globals['_STTSERVICE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
