# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tts_service_pb2 as tts__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tts_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSServiceStub(object):
    """TTS Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynthesizeSpeech = channel.unary_unary(
                '/tts.TTSService/SynthesizeSpeech',
                request_serializer=tts__service__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__service__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.StreamAudio = channel.unary_stream(
                '/tts.TTSService/StreamAudio',
                request_serializer=tts__service__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__service__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.GetAvailableVoices = channel.unary_unary(
                '/tts.TTSService/GetAvailableVoices',
                request_serializer=tts__service__pb2.GetVoicesRequest.SerializeToString,
                response_deserializer=tts__service__pb2.GetVoicesResponse.FromString,
                _registered_method=True)


class TTSServiceServicer(object):
    """TTS Service
    """

    def SynthesizeSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynthesizeSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeSpeech,
                    request_deserializer=tts__service__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__service__pb2.SynthesizeResponse.SerializeToString,
            ),
            'StreamAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=tts__service__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__service__pb2.AudioChunk.SerializeToString,
            ),
            'GetAvailableVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableVoices,
                    request_deserializer=tts__service__pb2.GetVoicesRequest.FromString,
                    response_serializer=tts__service__pb2.GetVoicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService(object):
    """TTS Service
    """

    @staticmethod
    def SynthesizeSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/SynthesizeSpeech',
            tts__service__pb2.SynthesizeRequest.SerializeToString,
            tts__service__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TTSService/StreamAudio',
            tts__service__pb2.SynthesizeRequest.SerializeToString,
            tts__service__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/GetAvailableVoices',
            tts__service__pb2.GetVoicesRequest.SerializeToString,
            tts__service__pb2.GetVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
