apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-gateway
  labels:
    app: ai-assistant
    component: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-assistant
      component: gateway
  template:
    metadata:
      labels:
        app: ai-assistant
        component: gateway
    spec:
      containers:
      - name: gateway
        image: ai-assistant-gateway:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: KEYCLOAK_SERVER_URL
          value: "http://keycloak-service:8080"
        - name: KEYCLOAK_REALM
          value: "ai-assistant"
        - name: KEYCLOAK_CLIENT_ID
          value: "ai-assistant-client"
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-assistant-secrets
              key: keycloak-client-secret
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ai-assistant-secrets
              key: access-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-assistant-secrets
              key: openai-api-key
        - name: ELEVENLABS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-assistant-secrets
              key: elevenlabs-api-key
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: ai-assistant
    component: gateway
spec:
  type: LoadBalancer
  selector:
    app: ai-assistant
    component: gateway
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
