apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: ai-assistant
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-assistant
      component: redis
  template:
    metadata:
      labels:
        app: ai-assistant
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: ai-assistant
    component: redis
spec:
  selector:
    app: ai-assistant
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
